#!/bin/ash

source /root/variables

export PATH='/usr/bin:/usr/sbin:/bin:/sbin'

has_offer=0
count=0
connection=""
logread -f |while read line; do
	echo "${line}" | grep -q "ag71xx-mdio.0:00: Port"
	if [ $? == 0 ]; then
		ports=$(echo "${line}" | grep -oE "Port ([0-9]+) is (up|down)")
		date=$(echo "${line}" | grep -oE "^[a-zA-Z]+[[:space:]]+[a-zA-z]+[[:space:]]+[0-9]+[[:space:]]+[0-9:]+ [0-9]+")
		pnum=$(echo "${ports}" | cut -d ' ' -f 2)	
		state=$(echo "${ports}" | cut -d ' ' -f 4)	
		#echo "From: ${From}"$'\n'"To: ${To}"$'\n'"Subject: [openwrt] Port ${pnum} is ${state}"$'\n\n'"Data: ${date}"$'\n'"Porta: ${pnum}"$'\n'"Estado: ${state}" | ssmtp "${Sender}"
		telegram=$(echo "*Port:* ${pnum}"$'\n'"*Data:* ${date}"$'\n'"*State:* ${state}")
		#echo $telegram >>/tmp/log/lanports.log
		/root/telebot "$telegram"
	fi
	echo "${line}" | grep -q "DHCPOFFER" 
	if [ $? == 0 ]; then
		has_offer=1
		count=4
	fi

	echo "${line}" | grep -q "DHCPACK" 
	if [ $? == 0 ] && [ $has_offer == 1 ]; then 
		connection=""
		macaddr2=$(iw dev wlan0 station dump | grep Station | grep -oE "([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}" | awk '{printf $0 " "}')
		macaddr3=$(iw dev wlan1 station dump | grep Station | grep -oE "([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}" | awk '{printf $0 " "}')
		dados=$(echo "${line}" | grep -oE "[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3} \w{2}:\w{2}:\w{2}:\w{2}:\w{2}:\w{2} \w+")
		date=$(echo "${line}" | grep -oE "^[a-zA-Z]+[[:space:]]+[a-zA-z]+[[:space:]]+[0-9]+[[:space:]]+[0-9:]+ [0-9]+")
		ip=$(echo "${dados}" | cut -d ' ' -f 1)
		macaddr=$(echo "${dados}" | cut -d ' ' -f 2)
		date=$(/root/plugins/get_date)
		for item in ${macaddr2}
		do
			if [ "$item" == "$macaddr" ]; then
				connection="has connected to *2.4 GHz* WiFi on this router"
			fi 
		done
		for item in ${macaddr3}
                do
                        if [ "$item" == "$macaddr" ]; then
                                connection="has connected to *5.0 GHz* WiFi on this router"
                        fi
                done
		macaddr=$(echo $macaddr | awk '{print toupper($0)}')
		name=$(echo "${dados}" | cut -d ' ' -f 3 | awk '{gsub("*","\*"); gsub( "_","\_" );  printf $0 }')
		#echo "From: ${From}"$'\n'"To: ${To}"$'\n'"Subject: [openwrt] DHCP-ACK ${name} has ${ip}"$'\n\n'"Time: ${date}"$'\n'"IP Assigned: ${ip}"$'\n'"MAC Address: ${macaddr}" | ssmtp "${Sender}"
		if [ -z "$connection" ]; then
			connection=" has connected to your other router"
		fi
		telegram=$(echo "${model}"$'\n'"${version}"$'\n'"${date}"$'\n\n''_'"Device Connection Monitor"'_'$'\n'"${name} ${connection}"$'\n'"*Time Connected:* ${date}"$'\n'"*IP Assigned:* ${ip}"$'\n'"*Mac Address:* ${macaddr}")
		curl -k -s -X POST $api/sendMessage -d chat_id=$my_chat_id -d parse_mode=Markdown --data-urlencode text="$telegram" &>/tmp/telegram.log
		#echo $telegram >>/tmp/log/lanports.log
		#/root/telebot "$telegram"
		has_offer=0
	fi
	if [ $count == 0 ]; then
		has_offer=0
	else
		count=$((count-1))
	fi
done&
